const randomVoyage = () => {
  const testArr = [
    "https://youtu.be/ZpOTsdIy6Do",
    "https://youtu.be/UwjhmWZPTUA",
    "https://youtu.be/3kz-k3Hz8jM",
    "https://youtu.be/of4daiipDFg",
    "https://youtu.be/9MNo5Y9m3O0 ",
    "https://youtu.be/jat1ndHrvmQ",
    "https://youtu.be/BXopqftCjAg",
    "https://youtu.be/AawUYHgpOjQ , https://youtu.be/mpIGWynU9M0",
    ": https://youtu.be/ffbvbLxFGj0",
    ": https://youtu.be/WFFCMuKeLUc",
    ": https://youtu.be/dE-iXHZrAls",
    ": https://youtu.be/gqzsM1_ByNw",
    ": https://youtu.be/iZITuNb8lOI",
    ": https://youtu.be/MawAxkNy-ek",
    ": https://youtu.be/TSWH6Gd4LlI",
    ": https://youtu.be/wFWVCgOzvms",
    ": https://youtu.be/ChOL2trWOWo",
    ": https://youtu.be/Vs88rR3jHIA",
    ": https://youtu.be/Z2FFezpsVG4",
    ": https://youtu.be/ez_Yxz6LCIY",
    ": https://youtu.be/w6cS-Tap_XM",
    ": https://youtu.be/hlWK3rRSK_Q",
    ": https://youtu.be/OGKCNb2-KfQ",
    ": https://youtu.be/m-tlGvAamX4",
    ": https://youtu.be/l5F3WYsGvYk",
    ": https://youtu.be/7x0NFCzTm_s",
    ": https://youtu.be/jRODTyCvFzQ",
    ": https://youtu.be/rDHXu7TvBe8",
    ": https://youtu.be/t6U_0mAl3Vo",
    ": https://youtu.be/6pq2U-Sjh1k",
    ": https://youtu.be/D2jlIsLeC7A",
    ": https://youtu.be/0RckceBrd5s",
    ": https://youtu.be/ztEGA26TzW0",
    ": https://youtu.be/fTSh8DS_pQs , https://youtu.be/v8Xg3vRGW_M",
    ": https://youtu.be/0T-7aa7l1N0 , https://youtu.be/_3Hm_SRvuNI",
    ": https://youtu.be/5bRYORdlP1k",
    ": https://youtu.be/BD2ZSJINNLc , https://youtu.be/PytMSi5CSL8",
    ": https://youtu.be/7kC_OUWFINw",
    ": https://youtu.be/9Kf9aIagOLY",
    ": https://youtu.be/H-5HGNFP--Q",
    ": https://youtu.be/7_Cdcv56L10",
    ": https://youtu.be/Pta5_Dlm2ng",
    ": https://youtu.be/-kQFxZUpaZY",
    ": https://youtu.be/LcZ3V4upIE0 , https://youtu.be/THmbobT_NXE",
    ": https://youtu.be/lqpqTa60tTI",
    ": https://youtu.be/LYfqJjh2GnU",
    ": https://youtu.be/E-s-8-1go6I , https://youtu.be/of4C--cdq18",
    ": https://youtu.be/2OJu52IrB6Q",
    ": https://youtu.be/7v_k2zn0yoY",
    ": https://youtu.be/-G1TN41QrGo",
    ": https://youtu.be/c6ta7Wfbi74",
    ": https://youtu.be/GiAD-5I-mZ0",
    ": https://youtu.be/QJXmDity8ns",
    ": https://youtu.be/cHNwHod8pyY",
    ": https://youtu.be/VvuyR1mMOHw",
    ": https://youtu.be/izgVVkRkg68 , https://youtu.be/wxQwmKsK5E4",
    ": https://youtu.be/lpG2jRaGhA4",
    ": https://youtu.be/y8JRrjymlb0",
    ": https://youtu.be/I_XfL-chCHg",
    ": https://youtu.be/zQ44TULWeE8",
    ": https://youtu.be/HFh9cJe6_ck",
    ": https://youtu.be/ZxKGy_xlPzc",
    ": https://youtu.be/Kn98KHK7MDo",
    ": https://youtu.be/bCHTPlomvmk",
    ": https://youtu.be/IXOibAYuSfY , https://youtu.be/GXnv0hr1rgQ",
    ": https://youtu.be/dPxkijx9LN0",
    ": https://youtu.be/jWqFxW41P4M",
    ": https://youtu.be/Z7kavGSnND0",
    ": https://youtu.be/2Qo8kUbcFXI",
    ": https://youtu.be/t3JcB8pMb9Y",
    ": https://youtu.be/6rcdw-XV1oE",
    ": https://youtu.be/VOpOv-wdIlI",
    ": https://youtu.be/-U5v6XMbLfg",
    ": https://youtu.be/9XHKxPKmPZo",
    ": https://youtu.be/yS2ughGxP_M",
    ": https://youtu.be/gaqMWu-hf7w",
    ": https://youtu.be/AbEJYwsLpL4",
    ": https://youtu.be/rA6OsMt4LZU",
    ": https://youtu.be/9r9e9c9pENM",
    ": https://youtu.be/oLbb1lPORIQ",
    ": https://youtu.be/PwU5tornlp8 , https://youtu.be/V14DjTcERPM",
    ": https://youtu.be/xcSIcg9Ehzs",
    ": https://youtu.be/5cLei13hrQQ",
    ": https://youtu.be/aa8qSqJniLo",
    ": https://youtu.be/ad4c2XSUowU",
    ": https://youtu.be/xJAlNqeshVI",
    ": https://youtu.be/b0SDvITQsmE",
    ": https://youtu.be/jRSnyLYd3rc",
    ": https://youtu.be/hueHqUJddpU",
    ": https://youtu.be/trRxASzZR80",
    ": https://youtu.be/nC1hRljBh_s",
    ": https://youtu.be/uNWhuDU80ms",
    ": https://youtu.be/OnHqLea9Ch4",
    ": https://youtu.be/_iiv16TppK8",
    ": https://youtu.be/av0BgwNxs0k , https://youtu.be/cbrzJEz4xZg",
    ": https://youtu.be/7P7ZL6MD9R0 ",
    ": https://youtu.be/lubYafr_51E",
    ": https://youtu.be/uWLDWZ_TFxY",
    ": https://youtu.be/MRD7P2zVf5E",
    ": https://youtu.be/GxgnaeoRCQg",
    ": https://youtu.be/SW7j-ng07CY",
    ": https://youtu.be/5ShHysWJrSY",
    ": https://youtu.be/YrHTmdE6Sxs",
    ": https://youtu.be/BQNJGil4BOU",
    ": https://youtu.be/U04l6OdtxDE",
    ": https://youtu.be/xBrcIRHtOAE",
    ": https://youtu.be/lr_gqqzkqzE",
    ": https://youtu.be/2aVSDmrDlyY",
    ": https://youtu.be/ZDzbO1W03TQ ",
    ": https://youtu.be/ljBc1fb6Wpg",
    ": https://youtu.be/tf58HCC0Jwo",
    ": https://youtu.be/BltYAUo0Qbc",
    ": https://youtu.be/WZxOsjo3FaY",
    ": https://youtu.be/Mzdd0KSi76E",
    ": https://youtu.be/9Pdpl36dQDk",
    ": https://youtu.be/EeIC220Ag8k",
    ": https://youtu.be/CF9kSuksdhA",
    ": https://youtu.be/2wJyZZGenhY",
    ": https://youtu.be/K-DK-AoNM5c",
    ": https://youtu.be/1IlaMnHPmE4",
    ": https://youtu.be/_0VZwhWa5e0",
    ": https://youtu.be/ziw9Mzxqcpw",
    ": https://youtu.be/u4q5QhaMSjk , https://youtu.be/hbHUpOXim1I",
    ": https://youtu.be/FNkQ2eGmmuw",
    ": https://youtu.be/vKsV6vrC_YM , https://youtu.be/TMd70gYDf9s",
    ": https://youtu.be/VxO1AGvz1yo",
    ": https://youtu.be/7e1nzgkGAVI",
    ": https://youtu.be/TqcBs-f_8Rs",
    ": https://youtu.be/-T-Q3K0FxCc",
    ": https://youtu.be/ScPMCdbJSQ4 ",
    ": https://youtu.be/KTwLA7U48s8",
    ": https://youtu.be/FKLA6tcoVAk , https://youtu.be/uKH8JSGNnb8",
    ": https://youtu.be/tiVKZeM2lAI",
    ": https://youtu.be/Q3iOhJ54Zb0",
    ": https://youtu.be/0L5MeogxFVI",
    ": https://youtu.be/RYp3_gXJPiw ",
    ": https://youtu.be/ZBqANejugUY",
    ": https://youtu.be/tv87YpNV4ws , https://youtu.be/yCfhrqave88",
    ": https://youtu.be/9Qswzkoj7B4",
    ": https://youtu.be/s4KjsDyYU44",
    ": https://youtu.be/SvjsAKpk7w8",
    ": https://youtu.be/-s2qNawILig",
    ": https://youtu.be/SbyzbseMAbU",
    ": https://youtu.be/quNiW94-eXA",
    ": https://youtu.be/4oKHwgWfrrU",
    "[6/6/2022 6:14PM] The_Gaming_Galleon: and we washed ourselves clean in the que...and it was good."
  ];

  const randomNumber = Math.floor(Math.random() * testArr.length);
  const randomQuote = testArr[randomNumber];
  return randomQuote;
};

module.exports = {
  randomVoyage,
};
